# Generated by Django 4.2.5 on 2023-09-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_id_product_iuuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iuuid',
            new_name='uuid',
        ),
    ]
